from app.core.db import Base, engine, SessionLocal
from app import models
from app.rag.ingest import chunk_text

SEED_DOCS = [
    dict(
        title="Cooperative society - general definition",
        issuer="Ministry of Cooperation / ICA",
        source_url="https://cooperation.gov.in",
        status="approved",
        last_verified_at="2026-01-15",
        text=(
            "A cooperative society is an autonomous association of persons united voluntarily to meet their "
            "common economic, social, and cultural needs through a jointly owned and democratically controlled "
            "enterprise. It operates strictly on the principle of one-member-one-vote, ensuring that capital "
            "investment does not dictate voting power. Any net surplus generated by the cooperative is distributed "
            "equitably among members as patronage dividend or allocated to reserve funds, rather than being "
            "distributed to outside commercial investors."
        ),
    ),
    dict(
        title="PACS - primary agricultural credit society",
        issuer="Ministry of Cooperation / NCDC",
        source_url="https://cooperation.gov.in/pacs",
        status="approved",
        last_verified_at="2026-01-15",
        text=(
            "A PACS (Primary Agricultural Credit Society) is the foundational village-level cooperative institution "
            "in India's three-tier cooperative credit structure. PACS provides farmer members with short-term crop loans "
            "through the Kisan Credit Card (KCC), distributes subsidized fertilizers, certified seeds, and agricultural inputs, "
            "maintains community storage godowns, and operates Fair Price Shops (PDS). Under the Ministry of Cooperation's "
            "National PACS Computerization Project, PACS are upgraded with cloud ERP software, micro-ATMs, and Common Service "
            "Center (CSC) capabilities for delivering digital public services directly in rural villages."
        ),
    ),
    dict(
        title="PACS membership and governance",
        issuer="National Federation of State Cooperative Banks (NAFSCOB)",
        source_url="https://nafscob.org",
        status="approved",
        last_verified_at="2026-01-15",
        text=(
            "To become a member of a Primary Agricultural Credit Society (PACS), an applicant must be a resident of "
            "the society's operational area and engaged in farming or rural craftsmanship. The applicant must submit a "
            "prescribed membership application along with land ownership records (Khasra/Khatoni or tenant agreement), "
            "Aadhaar card, passport photographs, and pay the nominal admission fee and minimum share capital. Every member "
            "enjoys equal voting rights in the Annual General Meeting (AGM) to elect the Board of Directors or Managing "
            "Committee on a one-member-one-vote basis."
        ),
    ),
    dict(
        title="Crop insurance - general guidance",
        issuer="Ministry of Agriculture & Farmers Welfare",
        source_url="https://pmfby.gov.in",
        status="approved",
        last_verified_at="2026-01-15",
        text=(
            "Crop insurance protects farmers against catastrophic financial losses resulting from non-preventable natural "
            "hazards such as drought, floods, unseasonal rainfall, hailstorms, pest infestations, and post-harvest damage. "
            "In India, the primary national crop insurance program is the Pradhan Mantri Fasal Bima Yojana (PMFBY). Farmers "
            "can enroll through commercial bank branches, regional rural banks, PACS, Common Service Centers (CSCs), or directly "
            "online on the National Crop Insurance Portal (pmfby.gov.in) before the seasonal cut-off date."
        ),
    ),
    dict(
        title="Pradhan Mantri Fasal Bima Yojana - rules and claims",
        issuer="PMFBY National Guidelines",
        source_url="https://pmfby.gov.in/guidelines",
        status="approved",
        last_verified_at="2026-01-15",
        text=(
            "Under the Pradhan Mantri Fasal Bima Yojana (PMFBY), the premium payable by the farmer is capped at 2 percent "
            "of the sum insured for all Kharif food grains and oilseeds, 1.5 percent for all Rabi food grains and oilseeds, "
            "and 5 percent for annual commercial and horticultural crops. In case of localized calamities like hailstorms, "
            "landslides, cloudbursts, or waterlogging (inundation), the farmer must report crop loss within a strict, mandatory "
            "72-hour cut-off window to the designated insurance company, local agriculture office, or the 14447 helpline. "
            "Required documentation for claim processing includes land ownership record (Khasra/Khatoni), sowing certificate "
            "(Girdawari) issued by the Patwari, and bank account passbook copy."
        ),
    ),
    dict(
        title="Financial literacy - interest and savings",
        issuer="Reserve Bank of India / NABARD",
        source_url="https://nabard.org",
        status="approved",
        last_verified_at="2026-01-15",
        text=(
            "Financial literacy guides rural households in sound debt management, credit planning, and savings security. "
            "Under the Kisan Credit Card (KCC) scheme, short-term crop loans up to 3 lakh rupees receive an interest subvention "
            "from the Government: while the base interest rate is 7 percent per annum, farmers who repay promptly within one "
            "year receive a 3 percent Prompt Repayment Incentive (PRI), resulting in an effective interest rate of only 4 percent. "
            "Farmers are strongly cautioned against informal moneylenders who charge exorbitant compound rates. To prevent fraud, "
            "never disclose one-time passwords (OTP), UPI PINs, or bank passwords to any caller; banks and government officials "
            "never demand your secret PIN or password."
        ),
    ),
    dict(
        title="Filing a grievance - general process",
        issuer="Department of Administrative Reforms & Public Grievances",
        source_url="https://pgportal.gov.in",
        status="approved",
        last_verified_at="2026-01-15",
        text=(
            "A grievance is a formal complaint regarding delayed services, wrongful claim rejection, unauthorized deductions, "
            "or cooperative governance disputes. For PMFBY crop insurance grievances, farmers can register complaints directly on "
            "the National Crop Insurance Portal (pmfby.gov.in), call the Kisan Call Center at toll-free number 1800-180-1551, or "
            "approach the District Level Grievance Redressal Committee (DGRC) chaired by the District Collector. For PACS and "
            "cooperative society complaints, written petitions with documentary evidence and transaction receipts should be submitted "
            "to the Assistant Registrar of Cooperative Societies (ARCS) or through the national CPGRAMS portal (pgportal.gov.in)."
        ),
    ),
    dict(
        title="Cooperative governance - elections and audits",
        issuer="Multi-State Cooperative Societies Act & State Acts",
        source_url="https://cooperation.gov.in/acts",
        status="approved",
        last_verified_at="2026-01-15",
        text=(
            "Cooperative governance requires democratic accountability and fiscal transparency. A cooperative's Board of "
            "Directors is elected by members in accordance with statutory election rules. The society must convene an Annual "
            "General Meeting (AGM) within six months of the close of each financial year to review operational performance and "
            "approve accounts. Additionally, every cooperative is legally mandated to undergo an annual statutory audit by a certified "
            "auditor appointed from the panel approved by the Registrar of Cooperative Societies. Internal disputes must be referred "
            "to the Registrar of Cooperative Societies or the Cooperative Court rather than civil courts."
        ),
    ),
    dict(
        title="Government scheme discovery - general guidance",
        issuer="Ministry of Agriculture & Farmers Welfare",
        source_url="https://agricoop.nic.in",
        status="approved",
        last_verified_at="2026-01-15",
        text=(
            "Government schemes provide vital income support, capital grants, and farm infrastructure subsidies. Flagship initiatives "
            "include PM-KISAN, which transfers 6,000 rupees per year directly into eligible farmer bank accounts in three equal "
            "four-monthly installments of 2,000 rupees upon successful e-KYC and land seeding; the PM Kisan Maandhan Yojana, which "
            "provides a guaranteed monthly pension of 3,000 rupees to small and marginal farmers aged 18 to 40 after attaining age 60; "
            "and the Agriculture Infrastructure Fund (AIF), providing a 3 percent interest subvention for establishing cold storage, "
            "warehousing, and sorting facilities up to 2 crore rupees."
        ),
    ),
    dict(
        title="Sample scheme XYZ - awaiting verification",
        issuer="Unverified upload",
        source_url=None,
        status="pending",
        last_verified_at=None,
        text=(
            "Draft notes about sample scheme XYZ that have not yet been verified against official government gazettes. "
            "This document is marked pending and is strictly excluded from RAG retrieval until formally approved by an administrator."
        ),
    ),
]


def seed():
    Base.metadata.create_all(bind=engine)
    db = SessionLocal()
    try:
        if db.query(models.Document).count() > 0:
            return
        for d in SEED_DOCS:
            doc = models.Document(
                title=d["title"], issuer=d["issuer"], source_url=d["source_url"],
                status=d["status"], last_verified_at=d["last_verified_at"], language="en",
            )
            db.add(doc)
            db.flush()
            for piece in chunk_text(d["text"]):
                db.add(models.Chunk(document_id=doc.id, text=piece))
        db.commit()
    finally:
        db.close()


if __name__ == "__main__":
    seed()
    print("Seeded database.")
